# Generated by Django 3.2.18 on 2023-02-20 21:05

import django.core.serializers.json
from django.db import migrations, models
import nautobot.core.fields
import nautobot.extras.models.mixins
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0047_enforce_custom_field_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='IxiaRowModel24',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('module', models.CharField(max_length=200)),
                ('slug', nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from='module', unique=True)),
                ('port', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('tenant', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.CreateModel(
            name='IxiaRowModel14',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('module', models.CharField(max_length=200)),
                ('slug', nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from='module', unique=True)),
                ('port', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('tenant', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
    ]
