# Generated by Django 3.2.18 on 2023-02-26 20:07

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.fields
import nautobot.extras.models.mixins
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_auto_slug'),
        ('extras', '0054_scheduledjob_kwargs_request_user_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='IxiaRow24',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('module', models.CharField(max_length=200)),
                ('speed', models.CharField(default='10G', max_length=200)),
                ('slug', nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from='module', unique=True)),
                ('port', models.PositiveIntegerField(default='1')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('ntm', models.CharField(blank=True, default='Format eg.NTM1 M2 P36', max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ixiarow24s', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'IXIA Row 24 Port',
                'verbose_name_plural': 'IXIA Row 24 Ports',
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.CreateModel(
            name='IxiaRow14',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('module', models.CharField(max_length=200)),
                ('speed', models.CharField(default='10G', max_length=200)),
                ('slug', nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from='module', unique=True)),
                ('port', models.PositiveIntegerField(default='1')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('ntm', models.CharField(blank=True, default='Format eg.NTM1 M2 P36', max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'IXIA Row 14 Port',
                'verbose_name_plural': 'IXIA Row 14 Ports',
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.CreateModel(
            name='IxiaAppServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('username', models.CharField(max_length=200)),
                ('slug', nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from='username', unique=True)),
                ('password', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
    ]
