# Generated by Django 3.2.18 on 2023-03-05 18:42

from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenancy', '0002_auto_slug'),
        ('nautobot_plugin_ixia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ixiarow14',
            name='assigned_object_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ixiarow14',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'dcim'), ('model', 'interface'))), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ixiarow14s', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='ixiarow14',
            name='slug',
            field=nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from='assigned_object_type', unique=True),
        ),
        migrations.AddField(
            model_name='ixiarow14',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ixiarow14s', to='tenancy.tenant'),
        ),
    ]
