# Generated by Django 3.2.18 on 2023-02-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0047_enforce_custom_field_slug'),
        ('nautobot_plugin_ixia', '0002_ixiaappserver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IxiaRowModel14',
            new_name='IxiaRow14',
        ),
        migrations.RenameModel(
            old_name='IxiaRowModel24',
            new_name='IxiaRow24',
        ),
    ]
