# Generated by Django 3.2.18 on 2023-03-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_auto_slug'),
        ('nautobot_plugin_ixia', '0002_auto_20230305_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='ixiaappserver',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ixiaappservers', to='tenancy.tenant'),
        ),
    ]
