# Generated by Django 3.2.18 on 2023-02-28 02:37

from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.statuses


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_ixia', '0003_ixiaappserver_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ixiaappserver',
            name='status',
            field=nautobot.extras.models.statuses.StatusField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nautobot_plugin_ixia_ixiaappserver_related', to='extras.status'),
        ),
    ]
