# Generated by Django 3.2.18 on 2023-03-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_ixia', '0003_ixiaappserver_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ixiarow14',
            options={'verbose_name': 'IXIA Row 14 Port', 'verbose_name_plural': 'IXIA Row 14 Ports'},
        ),
    ]
