# Generated by Django 3.2.18 on 2023-02-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_ixia', '0003_auto_20230221_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='ixiarow14',
            name='speed',
            field=models.CharField(default='10G', max_length=200),
        ),
        migrations.AddField(
            model_name='ixiarow24',
            name='speed',
            field=models.CharField(default='10G', max_length=200),
        ),
    ]
