# Generated by Django 3.2.18 on 2023-02-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_ixia', '0004_auto_20230222_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='ixiaappserver',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
