# Generated by Django 3.2.18 on 2023-02-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_ixia', '0004_ixiaappserver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ixiarow14',
            name='port',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ixiarow24',
            name='port',
            field=models.PositiveIntegerField(),
        ),
    ]
