# Generated by Django 3.2.18 on 2023-02-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_ixia', '0005_ixiarow14_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ixiarow14',
            name='ntm',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ixiarow24',
            name='ntm',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
