# Generated by Django 3.2.18 on 2023-02-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_ixia', '0007_alter_ixiarow24_ntm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ixiarow24',
            name='ntm',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
